### ISSUE TITLE
name must be required and done must be false by default

### ISSUE THREAD

**Issue by ynotrusso** [connorreese13/03-todo-list-api#3]
https://github.com/connorreese13/03-todo-list-api/blob/207f311e5d2eda524d70b350572a7f5dde507031/models/items.js#L4

**Comment by connorreese13** [comment]
fixed on commit aef91931c1675100aa6342b70ee88f20a79f6e8e 

`let Items = mongoose.model("items", {
  name: {
    type: String,
    required: [true, "name is required"]
  },
  done: {
    type: Boolean,
    default: false
  }
});`
