### ISSUE TITLE
DELETE requests don't take body

### ISSUE THREAD

**Issue by ynotrusso** [connorreese13/03-todo-list-api#5]
https://github.com/connorreese13/03-todo-list-api/blob/207f311e5d2eda524d70b350572a7f5dde507031/controllers/items.js#L26

**Comment by connorreese13** [comment]
`router.delete("/:id", (req, res) => {
  db_items.findByIdAndDelete(req.params.id).then(response => {
    res.send(response);
  });
});`

validated delete request works without req.body :)
